### ISSUE TITLE
Cannot compile with play 2.3.7

### ISSUE THREAD

**Issue by djonmayer** [jamesward/play-static-asset-optimizations#1]
I cannot compile this example with play 2.3.7. I got following error:

.../conf/routes:743: type mismatch;
[error]  found   : play.api.mvc.Action[_$1(in value $anonfun)] where type _$1(in value $anonfun)
[error]  required: play.api.mvc.Action[_$1(in lazy value controllers_StaticAssets_at421_invoker)]
[error] GET     /assets-static/:version/*file                                                                   controllers.StaticAssets.at(path="/public", version, file)
[error] one error found
[error](compile:compile) Compilation failed

**Comment by jamesward** [comment]
Play 2.3 has a better way of fingerprinting static assets so you should no longer use the more manual approach that this project takes.  Look for more details in the `Reverse routing and fingerprinting for public assets` section of the [Play 2.3 Assets Doc](https://www.playframework.com/documentation/2.3.x/Assets).
